version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /pro/node_modules
      - .:/pro
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /pro/node_modules
      - .:/pro
    command: ["npm", "run", "test"]